
name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE for all Python scripts
        run: |
          $ErrorActionPreference = "Stop"
          Get-ChildItem -Path . -Include *.py -Recurse -File | ForEach-Object {
            $scriptPath = $_.FullName
            Write-Host "Compiling $scriptPath"
            pyinstaller --onefile $scriptPath
            Remove-Item -Path "$(($_.BaseName)+'.spec')" -ErrorAction Ignore
          }

      - name: Upload EXE files
        uses: actions/upload-artifact@v2
        with:
          name: exe-files
          path: dist/
